### ISSUE TITLE
Add costume config to sample

### ISSUE THREAD

**Issue by MostafaEbrahimi** [ToastShaman/dropwizard-auth-jwt#26]
when I add sample config.yml file to your sample code get error .How can I solve this problem
```yaml

server:
  rootPath: "/api/v1/*"
 applicationConnectors:
    - type: http
      port: 8484
  adminConnectors:
    - type: http
      port: 8484

logging:
  level: INFO
```

```error
return singletonMap("token", jws.getCompactSerialization());
```
